# Generated by Django 5.2.5 on 2025-08-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_achievement_athleticprofile_certification_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_coach_i_c7ddb8_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="coach",
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_coach_id",
            field=models.CharField(
                blank=True,
                help_text="Coach ID for athlete-coach relationship",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="coach_id",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for coach-athlete relationships",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["coach_id"], name="accounts_us_coach_i_c7ddb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["assigned_coach_id"], name="accounts_us_assigne_ea8c8b_idx"
            ),
        ),
    ]
