# Generated by Django 5.2.5 on 2025-08-28 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_user_accounts_us_coach_i_c7ddb8_idx_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_assigne_ea8c8b_idx",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="assigned_coach_id",
            new_name="coach_assignment_id",
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_coach",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned coach (backward compatibility)",
                limit_choices_to={"user_type": "coach"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="athletes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["coach_assignment_id"], name="accounts_us_coach_a_77e6b5_idx"
            ),
        ),
    ]
