# Generated by Django 5.2.5 on 2025-08-28 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_user_accounts_us_assigne_ea8c8b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="assigned_coach",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned coach/mentor (both athletes and coaches can coach others)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
