# Generated by Django 5.2.5 on 2025-08-28 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_assigned_coach"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Coach"),
                            ("assistant", "Assistant Coach"),
                            ("specialist", "Specialist Coach"),
                            ("mentor", "Mentor"),
                            ("peer", "Peer Coach"),
                        ],
                        default="primary",
                        help_text="Type of coaching relationship",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="When this coaching relationship started",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When this coaching relationship ended (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this coaching relationship is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this coaching relationship",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        help_text="User providing coaching/mentoring",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        help_text="User being coached/mentored",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach Assignment",
                "verbose_name_plural": "Coach Assignments",
                "db_table": "accounts_coach_assignment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mentee"], name="accounts_co_mentee__f0257b_idx"
                    ),
                    models.Index(
                        fields=["coach"], name="accounts_co_coach_i_df8f59_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="accounts_co_is_acti_de4145_idx"
                    ),
                    models.Index(
                        fields=["assignment_type"],
                        name="accounts_co_assignm_e1202e_idx",
                    ),
                    models.Index(
                        fields=["start_date"], name="accounts_co_start_d_360678_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("mentee", "coach", "assignment_type"),
                        name="unique_active_coach_assignment",
                    )
                ],
            },
        ),
    ]
