# Generated by Django 5.2.5 on 2025-08-28 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_coachassignment"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_coach_a_77e6b5_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="assigned_coach",
        ),
        migrations.RemoveField(
            model_name="user",
            name="coach_assignment_id",
        ),
    ]
