# Generated by Django 5.2.5 on 2025-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_user_accounts_us_coach_a_77e6b5_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coachassignment",
            name="unique_active_coach_assignment",
        ),
        migrations.RemoveIndex(
            model_name="coachassignment",
            name="accounts_co_assignm_e1202e_idx",
        ),
        migrations.RemoveField(
            model_name="coachassignment",
            name="assignment_type",
        ),
        migrations.AddConstraint(
            model_name="coachassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("mentee", "coach"),
                name="unique_active_coach_assignment",
            ),
        ),
    ]
