# Generated by Django 5.2.5 on 2025-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0008_remove_coachassignment_unique_active_coach_assignment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="sports_involved",
            field=models.JSONField(
                default=list,
                help_text="Sports involved in this achievement (multiple selection from: running, cycling, swimming, triathlon)",
            ),
        ),
        migrations.AddField(
            model_name="coachachievement",
            name="sports_involved",
            field=models.JSONField(
                default=list,
                help_text="Sports involved in this coaching achievement (multiple selection from: running, cycling, swimming, triathlon)",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the achievement (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="coachachievement",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the achievement (optional)",
            ),
        ),
    ]
