# Generated by Django 5.2.5 on 2025-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_achievement_sports_involved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleticprofile",
            name="experience_years",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Years of experience in sports (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="athleticprofile",
            name="sports_involved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("running", "Running"),
                    ("cycling", "Cycling"),
                    ("swimming", "Swimming"),
                    ("triathlon", "Triathlon"),
                ],
                help_text="Primary sport involvement (optional)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="experience_years",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Years of coaching experience (optional)",
                null=True,
            ),
        ),
    ]
