# Generated by Django 5.2.5 on 2025-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_convert_sports_to_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="sports_involved",
        ),
        migrations.RemoveField(
            model_name="coachachievement",
            name="sports_involved",
        ),
        migrations.AlterField(
            model_name="athleticprofile",
            name="sports_involved",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Sports involved (multiple selection from: running, cycling, swimming, triathlon - optional)",
            ),
        ),
    ]
