# Generated by Django 5.2.5 on 2025-08-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_achievement_sports_involved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="issuing_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization that issued the certification (optional)",
                max_length=200,
            ),
        ),
    ]
