# Generated by Django 5.2.5 on 2025-08-28 17:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_certification_issuing_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="css",
            field=models.FloatField(
                blank=True,
                help_text="Critical Swim Speed - enter total seconds (convert from mm:ss using helper functions)",
                null=True,
                validators=[accounts.models.validate_css],
                verbose_name="CSS",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="fpp",
            field=models.FloatField(
                blank=True,
                help_text="Functional Power Profile in watts (e.g., 250)",
                null=True,
                validators=[accounts.models.validate_fpp],
                verbose_name="FPP",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mas",
            field=models.FloatField(
                blank=True,
                help_text="Maximum Aerobic Speed in km/h (e.g., 18.5)",
                null=True,
                validators=[accounts.models.validate_mas],
                verbose_name="MAS",
            ),
        ),
    ]
