# Generated by Django 5.2.5 on 2025-09-21 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_user_css_alter_user_fpp_alter_user_mas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleticprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="athletic_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
