# Generated by Django 5.2.5 on 2025-09-29 21:04

from django.db import migrations


def set_professional_experience_to_null(apps, schema_editor):
    ProfessionalProfile = apps.get_model("accounts", "ProfessionalProfile")
    Certification = apps.get_model("accounts", "Certification")
    CoachAchievement = apps.get_model("accounts", "CoachAchievement")

    profiles = ProfessionalProfile.objects.filter(experience_years=0)

    for profile in profiles.iterator():
        has_certifications = Certification.objects.filter(profile=profile).exists()
        has_achievements = CoachAchievement.objects.filter(profile=profile).exists()
        about_notes = (profile.about_notes or "").strip()

        if not has_certifications and not has_achievements and not about_notes:
            profile.experience_years = None
            profile.save(update_fields=["experience_years"])


def revert_professional_experience(apps, schema_editor):
    ProfessionalProfile = apps.get_model("accounts", "ProfessionalProfile")
    ProfessionalProfile.objects.filter(experience_years__isnull=True).update(experience_years=0)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_athleticprofile_user_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_professional_experience_to_null,
            revert_professional_experience,
        ),
    ]
