# Generated by Django 5.2.5 on 2025-09-30 17:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_set_professional_experience_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="",
                help_text="Local phone number without country code",
                max_length=20,
                validators=[accounts.models.validate_phone_number],
            ),
        ),
    ]
