# Generated by Django 5.1.3 on 2025-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_separate_phone_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture - stored in Cloudinary when USE_CLOUDINARY=True",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
