# Generated by Django 5.2.5 on 2025-08-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Duration of the training session (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Time of the training session (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="training_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complex nested structure for workout builder (optional)",
            ),
        ),
    ]
