# Generated by Django 5.2.5 on 2025-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_training_duration_alter_training_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="distance",
            field=models.FloatField(
                blank=True,
                help_text="Race distance in kilometers (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="location",
            field=models.CharField(
                blank=True, help_text="Race location (optional)", max_length=200
            ),
        ),
    ]
