# Generated by Django 5.2.5 on 2025-08-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_race_distance_alter_race_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="sport",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("cycling", "Cycling"),
                    ("swimming", "Swimming"),
                    ("triathlon", "Triathlon"),
                    ("other", "Other"),
                ],
                help_text="Sport type for this race",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="sport",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("cycling", "Cycling"),
                    ("swimming", "Swimming"),
                    ("strength", "Strength"),
                    ("other", "Other"),
                ],
                help_text="Sport type for this training",
                max_length=50,
            ),
        ),
    ]
