# Generated by Django 5.2.5 on 2025-09-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_race_sport_alter_training_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="description",
            field=models.TextField(
                blank=True, help_text="Additional race details (optional)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="distance",
            field=models.CharField(
                blank=True,
                help_text="Race distance description (optional)",
                max_length=100,
                null=True,
            ),
        ),
    ]
