# Generated by Django 5.2.5 on 2025-10-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_clean_complex_intervals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the training", max_length=255),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("cycling", "Cycling"),
                            ("swimming", "Swimming"),
                            ("strength", "Strength"),
                            ("other", "Other"),
                        ],
                        help_text="Sport type for this training",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "training_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Training builder structure (warmup, intervals, cooldown, etc.)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this training is visible to other users (future feature)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who created this training template (coach or athlete)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Training",
                "verbose_name_plural": "Saved Trainings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["creator", "sport"],
                        name="core_savedt_creator_024ef5_idx",
                    ),
                    models.Index(
                        fields=["sport", "is_public"],
                        name="core_savedt_sport_d6c484_idx",
                    ),
                ],
            },
        ),
    ]
